# FAQ

* Qual é a diferença entre np.array() e lista? O np.array() pode ser modelado com operações matemáticas.
* Por que organizar as coisas em vetores/matrizes? Eficiência.
<li>Por que aprender Álgebra Linear? Alguns algoritmos de Machine Learning (e.g. Redes Neurais, Support Vector Machine) e métodos (e.g. Principal Component Analysis) baseiam-se em matrizes para armazenar e processar dados. Além disso, problemas de sistema de equações com grandes quantidades de variáveis também são resolvidas em matriz.
    
# Fontes interessantes:
    
https://medium.com/swlh/linear-algebra-in-python-b967061e342a

https://stackoverflow.com/questions/52603487/speed-comparison-numpy-vs-python-standard

# Blocos de conhecimento

![](https://media.giphy.com/media/xUA7b0Klw8Wfor7FWo/giphy.gif)

In [124]:
#Biblioteca open-source específica para estruturas de vetores e matrizes
import numpy as np

In [125]:
#BLOCO 1: VETORES

#np.array()
vetor = np.array([1,2,3])
print(vetor)

#selecionar o primeiro elemento do vetor
print(vetor[0])

#selecionar os elementos de um vetor exceto o primeiro
print(vetor[1:])

[1 2 3]
1
[2 3]


In [126]:
#Vetor é uma lista? Não!

lista = [1,2,3]
vetor = np.array([1,2,3])

#teste lista
try:
    print('lista ao quadrado', lista ** 2)
except TypeError:
    print('lista ao quadrado: erro')
    
#teste vetor
try:
    print('vetor ao quadrado:', vetor ** 2)
except TypeError:
    print('vetor ao quadrado: erro')
    

lista ao quadrado: erro
vetor ao quadrado: [1 4 9]


In [127]:
#(EXTRA) Discussão de shape de vetores e matrizes com 1 linha
#fonte: https://stackoverflow.com/questions/17428621/python-differentiating-between-row-and-column-vectors

print(vetor)
print(vetor.shape)
print(vetor.T.shape)
print(vetor.shape == vetor.T.shape) #Como isso?

#Solução
vetor_fix = np.array([[1,2,3]])
print(vetor_fix)
print(vetor_fix.shape)
print(vetor_fix.T.shape)

[1 2 3]
(3,)
(3,)
True
[[1 2 3]]
(1, 3)
(3, 1)


In [128]:
#BLOCO 2: MATRIZES

matriz = np.array([[11,12,13],
                   [21,22,23],
                   [31,32,33]])
print(matriz)
print(matriz.shape)

#selecionar o elemento da linha 1 (posição 0) e coluna 1 (posição 0)
print(matriz[0][0])

#selecionar a linha 1 (posição 0) inteira
print(matriz[0])

#selecionar a coluna 1 (posição 0)inteira
print(matriz[:,1])

[[11 12 13]
 [21 22 23]
 [31 32 33]]
(3, 3)
11
[11 12 13]
[12 22 32]


In [129]:
#(EXTRA) algumas maneiras diferentes (e criativas) de se criar uma matriz

#alternativa A: np.matrix()
#obs.: funciona, mas não é recomendando (https://numpy.org/doc/stable/reference/generated/numpy.matrix.html)
alt_evitar = np.matrix([[1, 2], [3, 4]])
print(alt_evitar)

#alternativa B
alt_b = np.random.rand(3,3)
print(alt_b)

#alternativa C
alt_c = np.zeros((3,3))
print(alt_c)

#alternativa D
alt_d = np.ones((3,3))
print(alt_d)

#alternativa E
alt_e = np.arange(8).reshape(2,4)
print(alt_e)

#alternativa F
alt_f = alt_e.reshape(4,2)
print(alt_f)

[[1 2]
 [3 4]]
[[0.3926548  0.43122242 0.81647316]
 [0.18572785 0.53961538 0.52982462]
 [0.10884646 0.49990249 0.32419045]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


# Como a matriz pode nos ajudar?

![](https://media.giphy.com/media/sa0LyqJW402YM/giphy.gif)

In [130]:
#Resolução de sistemas de equações: exemplo

# matriz_a * vetor_b = vetor_c
# (3 x 2)    (2 x 1)   (3 x 1)
matriz_a = np.array([[1,2],[1,2],[1,2]])
print(matriz_a.shape)

vetor_b = np.array([[2],[2]])
print(vetor_b.shape)

vetor_c = np.dot(matriz_a, vetor_b)
print(vetor_c)
print(vetor_c.shape)

(3, 2)
(2, 1)
[[6]
 [6]
 [6]]
(3, 1)


In [131]:
#Resolução de sistemas de equações: caso "real"

#objetivo: somar os recursos em R$

#como: 
# 1) calcular os recursos em R$
# 2) somar tudo

#cotação em R$:
kinder_ovo = 7.5
dolar = 5.5
gasolina_l = 6

#bens materiais
bens_materiais = np.array([[4,3,1],
                           [5,2,6],
                           [1,1,1]])
print(bens_materiais.shape)

cotacao = np.array([[kinder_ovo],
                    [dolar],
                    [gasolina_l]])
print(cotacao.shape)

#bens_materiais * cotacao = bens_moeda
#  (3 x 3)        (3 x 1)    (3 x 1)
bens_moeda = np.dot(bens_materiais, cotacao)

print(bens_moeda.shape)
print(bens_moeda)
print(bens_moeda.sum())

(3, 3)
(3, 1)
(3, 1)
[[52.5]
 [84.5]
 [19. ]]
156.0


In [132]:
#(extra)...continuação:
#Obter a cotação com base nos bens materiais e bens em moeda:
# (bens_materiais * cotacao = bens_moeda) é a mesma coisa que (bens_materiais^-1 * bens_moeda = cotacao)
# caso a matriz de bens materiais seja de fato invertível

bens_materiais_inv = np.linalg.inv(bens_materiais)

print(bens_materiais_inv.shape)
print(bens_moeda.shape)

print(np.dot(bens_materiais_inv, bens_moeda))

(3, 3)
(3, 1)
[[7.5]
 [5.5]
 [6. ]]


# Eficiência

![](https://media.giphy.com/media/6Z3D5t31ZdoNW/giphy.gif)

In [133]:
#Teste de duração de execução de um código
#objetivo: multiplicar cada elemento por 2

#exemplo                       
lista = list(range(1,9999)) #p.s.: NÃO COLOCAR MAIS QUE 4 DÍGITOS!!!!!!
print(lista[0:10])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [134]:
#método 1: nativo do python

def metodo_nativo(lista):
    lista_output = []
    for elemento in lista:
        lista_output.append(elemento ** 2)

    return lista_output[0:10]

metodo_nativo(lista)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [135]:
#método 2: uso de vetores
import numpy as np

def metodo_algelin(lista):
    array = np.array(lista)
    array_output = array ** 2
    return array_output[0:10]

metodo_algelin(lista)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [136]:
#comparação de tempo de execução

#método 1
%timeit -n 10 -r 3 (metodo_nativo(lista))

#método 2
%timeit -n 10 -r 3 (metodo_algelin(lista))

2.77 ms ± 92.7 µs per loop (mean ± std. dev. of 3 runs, 10 loops each)
831 µs ± 134 µs per loop (mean ± std. dev. of 3 runs, 10 loops each)


# Visualização de Vetores

![](https://media.giphy.com/media/KzK0fvKs3pOwpMvHNQ/giphy.gif)

In [137]:
#definições iniciais
origem = [0,0,0]
A = [3,2,5]
B = [10,6,7]
C = A + B

#preparando os vetores para o gráfico
import pandas as pd
vetor_A = pd.DataFrame([origem, A], columns=list('XYZ'))
vetor_A['label'] = 'vetor A'

vetor_B = pd.DataFrame([A, B], columns=list('XYZ'))
vetor_B['label'] = 'vetor B'

vetor_C = pd.DataFrame([origem, B], columns=list('XYZ'))
vetor_C['label'] = 'vetor C'

df = pd.concat([vetor_A, vetor_B, vetor_C]).reset_index(drop=True)
print(df)

#gráfico interativo
import plotly.express as px
fig = px.line_3d(df, x='X', y='Y', z='Z', color='label')
fig.show()

    X  Y  Z    label
0   0  0  0  vetor A
1   3  2  5  vetor A
2   3  2  5  vetor B
3  10  6  7  vetor B
4   0  0  0  vetor C
5  10  6  7  vetor C
